services:
  api:
    build: .
    ports:
      - 5500:5000
    restart: always
  redis:
    image: 'redis:alpine'
    restart: always
    command: redis-server --requirepass ${REDIS_PW}
    env_file: .env
    volumes:
      - cache:/data
    ports:
      - 6379:6379
volumes:
  cache:
    driver: local
