services:
  api:
    build: .
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PW: ${REDIS_PW}
    ports:
      - 5000:5000
    restart: always
  redis:
    image: 'redis:alpine'
    restart: always
    command: redis-server --requirepass ${REDIS_PW}
    environment:
      REDIS_PW: ${REDIS_PW}
    volumes:
      - cache:/data
    ports:
      - 6379:6379
volumes:
  cache:
    driver: local
