services:
  api:
    build: .
    environment:
      PORT: ${PORT}
      DB_CONNECTION: ${DB_CONNECTION}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PW: ${REDIS_PW}
    ports:
      - ${PORT}:5000
    restart: always
  redis:
    image: 'redis:alpine'
    restart: always
    command: redis-server --requirepass ${REDIS_PW}
    environment:
      REDIS_PW: ${REDIS_PW}
    volumes:
      - cache:/data
    ports:
      - 6379:6379
volumes:
  cache:
    driver: local
